services:
    nginx_publish_stream_event.configuration:
        class: NginxPublishStreamEventBundle\Service\Configuration

    nginx_publish_stream_event.command:
        class: NginxPublishStreamEventBundle\Command\ConfigurationDumper
        tags:
            -  { name: console.command }