services:
    nginx_publish_stream_event.configuration:
        class: NginxPublishStreamEventBundle\Service\Configuration

    nginx_publish_stream_event.command:
        class: NginxPublishStreamEventBundle\Command\ConfigurationDumper
        tags:
            -  { name: console.command }


    test_endpoint:
        class: NginxPublishStream\Stream\Endpoint
        arguments: ['pub', 'lp']

    test_config:
        class: NginxPublishStream\Stream\Configuration
        arguments: ["http://localhost", 8080, "@test_endpoint"]
        tags:
            - { name: nginx.config, key: localhost }
